// Generated by CIRCT firtool-1.62.0
module alu(	// src/main/scala/test2.scala:4:7
  input        clock,	// src/main/scala/test2.scala:4:7
               reset,	// src/main/scala/test2.scala:4:7
  input  [1:0] io_fn,	// src/main/scala/test2.scala:5:16
  input  [7:0] io_a,	// src/main/scala/test2.scala:5:16
               io_b,	// src/main/scala/test2.scala:5:16
  output [7:0] io_y	// src/main/scala/test2.scala:5:16
);

  wire [3:0][7:0] _GEN = {{io_a % io_b}, {io_a / io_b}, {io_a - io_b}, {io_a + io_b}};	// src/main/scala/test2.scala:12:10, :14:18, :15:{23,31}, :16:{23,31}, :17:{23,31}, :18:{23,31}
  assign io_y = _GEN[io_fn];	// src/main/scala/test2.scala:4:7, :12:10, :14:18, :15:23, :16:23, :17:23, :18:23
endmodule

